# Site settings
title: Hadron ID
SEOTitle: Hadron ID
header-img: img/index_hadron2.jpg
# email: hadron.id@gmail.com
description: "research collaboration"
keyword: "hadron"
url: "http://hadronid.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hadronid/hadronid.github.io/tree/master" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "research collaboration"
sidebar-avatar: /img/hadronid.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
#zhihu_username:     qiubaiying
github_username:    hadronid
#facebook_username:  baiying.qiu.7
#jianshu_username:   e71990ada2fd
# twitter_username:   hadron_id




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: 3630b6487edb2259bb0e                            #生成的clientID
  clientSecret: b665b31ee5573c89e1d613d8d0be71e40f3b3c0b    #生成的clientSecret
  repo: hadronid.github.io    #仓库名称
  owner: hadronid    #github用户名
  admin: hadronid
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'G-HYX6V0F112'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


plugins:
  - jekyll-seo-tag


# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "aj.arifi",
        href: "https://ajarifi.github.io"
    },
]
